
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: camel-quarkus-backstage
  description: A cool quarkus app
  annotations:
    argocd/app-name: camel-quarkus-backstage-bootstrap
    backstage.io/kubernetes-id: camel-quarkus-backstage
    # It must be commented otherwise we cannot see the Tekton pipelines resources
    # backstage.io/kubernetes-namespace: demo
    backstage.io/source-location: url:https://github.com/svkcemk/camel-quarkus-backstage
    # The janus-idp.io/tekton allows to set the boolean value: isTektonCIAvailable which is used within the UI to enable/disable the TektonCIComponent
    janus-idp.io/tekton: camel-quarkus-backstage
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: svkcemk/
    # See: topology annotation: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology
    app.kubernetes.io/name: quarkus
    app.quarkus.io/quarkus-version: 3.12.2
  tags:
    - java
    - quarkus
  links:
    - url: https://camel-quarkus-backstage-demo.apps.qshift.snowdrop.dev/
      title: Quarkus application url
      icon: web
spec:
  type: service
  lifecycle: production
  owner: user:guest
  providesApis: [camel-quarkus-backstage-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: camel-quarkus-backstage-api
  description: A cool quarkus app
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition: 
    $text: openapi.yaml
