kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: camel-quarkus-backstage-m2-repo-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
